### ISSUE TITLE
ReferenceError: Can't find variable: cordova

### ISSUE THREAD

**Issue by confile** [leecrossley/cordova-plugin-shake-detection#12]
When running your plugin in the dev console I get the following error in the console when I refresh the page:

![webinformationen_-_mg_iphone_ _buddy_is_ _index_html](https://cloud.githubusercontent.com/assets/64265/5943781/1af75d90-a722-11e4-94ad-8400badced9a.png)

**Comment by leecrossley** [comment]
You can't run your cordova app in this way - this is nothing to do with the plugin.
In addition, this cordova plugin (like most) does not support the browser platform.

**Comment by confile** [comment]
Sorry I did not get your point. What was wrong?
