### ISSUE TITLE
Address the comments on the gist?

### ISSUE THREAD

**Issue by dandv** [leecrossley/cordova-plugin-shake-detection#14]
Hi Lee,

I know you [may not monitor your gists](http://ilee.co.uk/shake-gesture-detection-in-phonegap/), but [the gist](https://gist.github.com/leecrossley/4078996) for Shake.js has a lot of comments, some of which seem to bring up relevant issues:

* calling Math.abs with two parameters
* [callback stops triggering after first shake](https://gist.github.com/leecrossley/4078996#comment-820468)
* ["the math is just plain wrong"](https://gist.github.com/leecrossley/4078996#comment-1390560) and the fork was [mentioned on StackOverflow](http://stackoverflow.com/questions/13809974/how-to-detect-shake-event-with-cordova-android#comment23094649_13827631). Issues it [claims to fix](https://gist.github.com/ucavus/5418463#comment-819615):
  * The maths was a bit weird. It did not actually measure the difference in acceleration. (`Math.abs()` only takes one argument.)
  * It was not very configurable per usage
  * Error handling did nothing.
  * The function called on the shake event received no information about the gesture.
  * The same function only fired once since it was cleared after a shake event occurred.
  * You could only do one thing upon a shake. (This version allows multiple instances, but you'll probably only want to have one watching for shakes at any given time.)

**Comment by leecrossley** [comment]
Hey, thanks for the note. The gist is *very old* and the issues have all been addressed in this repository.

**Comment by dandv** [comment]
Hey @ucavus - looks like Lee has fixed at least some of the issues you reported - e.g. the [`Math.abs()` problem](https://github.com/leecrossley/cordova-plugin-shake-detection/blob/master/www/shake.js#L36) at least.

**Comment by dandv** [comment]
Thanks Lee. Update the gist to just point to the repo maybe? I see a bunch of links to the gist instead of the repo on SO, [random blogs](http://www.ivangabriele.com/cordova-detecting-shaking) etc.
