### ISSUE TITLE
winphone have a strange behavior

### ISSUE THREAD

**Issue by bau720123** [leecrossley/cordova-plugin-shake-detection#16]
hi @leecrossley 
awesome plugin
Android and iOS are all work done
but in winphone when I use
```
shake.startWatch(onShake, 40 , onError );
```
it will trigger the onError function and have a wrong message "No Result"

**Comment by leecrossley** [comment]
This is thrown by the cordova device motion plugin, usually if it can't get the current reading of the accelerometer or format the result: https://github.com/apache/cordova-plugin-device-motion/blob/3950ab7b6b3f8fb74896ec3ee0d77e52773a38c6/src/wp/Accelerometer.cs#L141

Which device is this on, hardware / os version? It might be best to report this to the cordova device motion plugin.

**Comment by bau720123** [comment]
thanks @leecrossley reply
my winphone is NOKIA Lumia 520，Windows Phone 8.1 (the original is 8.0)
and I found whenI use "navigator.accelerometer.getCurrentAcceleration" method，it can got x,y,z value correctly
but when I use "navigator.accelerometer.watchAcceleration" method，it will always got the error trigger

I don't know if it it a reason
