### ISSUE TITLE
Shake accuracy ( need to much energy for shake)

### ISSUE THREAD

**Issue by poshetz** [leecrossley/cordova-plugin-shake-detection#7]
Hi, i tryed out this plugin that works like a charm, thanks for it, just i wanted to ask if its possible to fire the shake at an accelaration lower point, cause actually the shake is fired but i have to use too much muscles and energy to make it fires.

Is it possible?

**Comment by leecrossley** [comment]
This is now possible in version 0.3.0, thanks to a PR: https://github.com/leecrossley/cordova-plugin-shake-detection#example

**Comment by poshetz** [comment]
terrific! thank you
